# Generated by Django 4.2.2 on 2023-08-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_balance_id_alter_condition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='condition_active',
        ),
        migrations.AddField(
            model_name='condition',
            name='name',
            field=models.CharField(default='baseline', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.condition'),
        ),
    ]
