# Generated by Django 4.2.2 on 2023-11-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_alter_balance_id_alter_condition_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='name',
            field=models.CharField(default='control', max_length=128),
            preserve_default=False,
        ),
    ]
