# Generated by Django 4.2.2 on 2023-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_remove_participant_condition_active_condition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='credibility',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
