# Generated by Django 4.2.2 on 2023-11-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_condition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='condition_active',
        ),
        migrations.AddField(
            model_name='participant',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.condition'),
        ),
    ]
