# Generated by Django 4.2.2 on 2023-12-08 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_remove_participant_condition_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
