# Generated by Django 4.2.2 on 2023-08-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_credibilitycounter'),
        ('chatbot', '0021_condition_credibility'),
    ]

    operations = [
    ]
