# Generated by Django 4.2.19 on 2025-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_studysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='portfolio_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
